services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  T3G\AgencyPack\Blog\:
    resource: '../Classes/*'

  T3G\AgencyPack\Blog\Hooks\PageLayoutHeaderHook:
    public: true

  T3G\AgencyPack\Blog\Service\CommentService:
    public: true
