name: CI

on:
  push:
    branches-ignore:
      - 'task/**'
      - 'bugfix/**'
      - 'feature/**'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        typo3: ['^11.5']
        php: ['7.4', '8.0', '8.1', '8.2']
        mysql: ['5.7', '8.0']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up MySQL ${{ matrix.mysql }}
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: ${{ matrix.mysql }}
          mysql root password: 'root'

      - name: Set up PHP version ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, php-cs-fixer

      - name: Environment Check
        run: |
          php --version
          composer --version

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies with typo3/cms-core:${{ matrix.typo3 }}
        run: |
          composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
          git checkout composer.json

      - name: Info
        run: composer info

      - name: Lint PHP
        run: composer t3g:test:php:lint

      - name: CGL
        run: php-cs-fixer fix --dry-run --verbose

      - name: Unit Tests with coverage
        run: composer t3g:test:php:unit:cover

      - name: Functional Tests with coverage
        run: composer t3g:test:php:functional:cover
        env:
          typo3DatabaseHost: 127.0.0.1
          typo3DatabaseName: t3func
          typo3DatabasePassword: root
          typo3DatabaseUsername: root
