name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        typo3: [^9.5]
        php: ['7.2', '7.3', '7.4']

    steps:
      - name: Start database server
        run: sudo /etc/init.d/mysql start

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PHP version ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, php-cs-fixer

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies with typo3/cms-core:${{ matrix.typo3 }}
        run: |
          composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
          git checkout composer.json

      - name: CGL
        run: php-cs-fixer fix --dry-run --verbose

      - name: Unit Tests
        run: composer t3g:test:php:unit

      - name: Functional Tests
        run: composer t3g:test:php:functional
        env:
          typo3DatabaseHost: 127.0.0.1
          typo3DatabaseName: t3func
          typo3DatabasePassword: root
          typo3DatabaseUsername: root
